# Site settings
title: Goteo Api Documentation
email: dev@goteo.org
description: > # Goteo API documentation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://developers.goteo.org" # the base hostname & protocol for your site
apiurl: "https://api.goteo.org/v1" # the base hostname & protocol for api
twitter_username: goteofunding
github_url: https://github.com/GoteoFoundation/goteo-api-doc
# api_spec: http://localhost:5000/spec
api_spec: https://api.goteo.org/v1/spec
analytics: UA-62675757-1
# Build settings
markdown: rdiscount

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'rakefile.rb', 'README.md', 'generate_examples.sh']